# Base configs
baseurl: "https://aaronmaharjan.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Aaron Maharjan"
subtitle: "Explore life through my lens"
author: "Aaron Maharjan"
header:
 title: "Photography"
 subtitle: "by Aaron Maharjan"
footer:
 name: "Namaste, My name is Aaron"
 bio: "I am a developer and lover of all things tech. I was born in Nepal and grew up in Dunedin, New Zealand."
 github: "Here is a link to the original which I forked from github, thanks Ram Patra <a href=\"https://github.com/ramswaroop/photography\"></a>"
web_design: "not me!"
#social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ram__patra"
#  instagram: "https://www.instagram.com/ram_patra"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
#  github: "https://www.github.com/rampatra"
